[package]
name = "coop-cloud-mdns-publisher"
version = "0.1.8"
edition = "2024"
authors = ["Jade Ambrose", "Merri-bek Tech Inc."]
rust-version = "1.96"
readme = "README.md"
homepage = "https://lores.tech/"
repository = "https://github.com/local-resilience-tech/coop-cloud-mdns-publisher/"
keywords = ["lores", "coop-cloud", "mdns", "avahi"]
license-file = "LICENSE.txt"
description = "Publishes Coop Cloud app services via mDNS/Avahi"

[package.metadata.deb]
name = "ccmdns"
maintainer = "Jade Ambrose <jade@merri-bek.tech>"
depends = "avahi-daemon, $auto"
section = "net"
priority = "optional"
assets = [
    { source = "target/release/ccmdns", dest = "/usr/bin/ccmdns", mode = "755" },
    { source = "README.md", dest = "/usr/share/doc/ccmdns/README.md", mode = "644" },
    { source = "debian/ccmdns.logrotate", dest = "/etc/logrotate.d/ccmdns", mode = "644" },
]
maintainer-scripts = "debian/"
systemd-units = { unit-name = "ccmdns", enable = true }

[[bin]]
name = "ccmdns"
path = "src/main.rs"

[dependencies]
bitflags = "2"
clap = { version = "4", features = ["derive"] }
coop-cloud-docker-apps = "0.2.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }

[profile.release]
strip = true
